"""create roles table

Revision ID: 3848f5e68f4c
Revises: 09e64aa7e2cd
Create Date: 2026-03-05 14:17:25.018844

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '3848f5e68f4c'
down_revision: str | Sequence[str] | None = '09e64aa7e2cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
